# Generated by Django 4.1.3 on 2023-01-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(choices=[('USA', 'USA'), ('CHINA', 'CHINA'), ('RUSSIA', 'RUSSIA'), ('INDIA', 'INDIA')], default='USA', max_length=15)),
                ('company', models.CharField(choices=[('USA', 'USA'), ('CHINA', 'CHINA'), ('RUSSIA', 'RUSSIA'), ('INDIA', 'INDIA')], default='NOT COMPANY', max_length=15)),
                ('succes', models.BooleanField(default=True)),
            ],
        ),
    ]
