# Generated by Django 4.1.3 on 2023-01-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
