# Generated by Django 4.1.3 on 2023-01-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_flight_flight_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='company',
            field=models.CharField(choices=[('USA', 'USA'), ('CHINA', 'CHINA'), ('RUSSIA', 'RUSSIA'), ('INDIA', 'INDIA'), ('OTHER', 'OTHER')], default='NOT COMPANY', max_length=15),
        ),
        migrations.AlterField(
            model_name='flight',
            name='country',
            field=models.CharField(choices=[('USA', 'USA'), ('CHINA', 'CHINA'), ('RUSSIA', 'RUSSIA'), ('INDIA', 'INDIA'), ('OTHER', 'OTHER')], default='USA', max_length=15),
        ),
    ]
