# Generated by Django 4.1.3 on 2023-01-10 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_flight_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
