# Generated by Django 4.1.3 on 2023-01-10 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_flight_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
