# Generated by Django 4.1.3 on 2023-01-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_flight_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='upload',
            field=models.ImageField(default='', upload_to='logo/'),
            preserve_default=False,
        ),
    ]
